# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGI0ZGQ0ZTk2ZjU1YzgyYjU5MTliZWIzZmFkNDEzZDRmNGY1OTQ5OWNlZjgyMDk4ZjZiMjg2MjNlNjBjMGNmNWZjOWYxNmY5YTQwNGU0ZmFlYWEyZDQ0OGYwZDgwNGE2OWE2NDA3M2NiYThkNTM2OTFlZGQ5OGU0MGJhZTE4ZjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
